polls/urls.py
#---------------------------------------------------------------
#- In this file I will define the url patterns of my polls app.
#---------------------------------------------------------------
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
               url(r"^$", views.IndexView.as_view(), name="index"),
               url(r"^signup$", views.SignupView.as_view(), name="signup"),
               url(r"^login$", login, kwargs={"template_name": "polls/login.html"}, name="login"),
               url(r"^accounts/(?P<pk>[0-9]+)$", views.UserAccountView.as_view(), name="accounts"),
               url(r"^logout$", logout, kwargs={"next_page": "polls:index"}, name="logout"),
               url(r"^create$", views.CreatePollView.as_view(), name="create-poll"),
               url(r"^update/(?P<pk>[0-9]+)$", views.UpdatePollView.as_view(), name="update-poll"),
               url(r"^delete/(?P<pk>[0-9]+)$", views.DeletePollView.as_view(), name="delete-poll"),
               url(r"^vote/(?P<pk>[0-9]+)$", views.VotePollView.as_view(), name="vote"),
               url(r"^results/(?P<pk>[0-9]+)$", views.ResultsPollView.as_view(), name="results"),
              ]

pollsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

# Examples:
# url(r'^$', 'pollsite.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),
#-----------------------------------------------------------
#- the url function takes te following arguments:
#-    * regex: regular expression to map againts defined
#-             urls.
#-    * view: the to which will be called upon the match.
#-    + kwargs: arguments passed to the target view.
#-    + name: name usde to reference across templates.
#-----------------------------------------------------------

urlpatterns = [
    url(r'^', include('polls.urls', namespace='polls')),               #- The ^ patterns are handled by polls.urls.
                                                                       #- The namespace is used to differenciate between
                                                                       #- views with the same name but different app.
    url(r'^admin/', include(admin.site.urls)),
]

polls/models.py
import datetime

from django.db import models
from django import forms
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.utils.encoding import force_unicode

# Create your models here.
#---------------------------------------------------------------
#- Models are the definitions of the data my application will
#- handle. Each model is a class (table in the database) and
#- each model will have some attributes (fileds in the table)
#- which will define the type of data and its behaviour.
#-
#- They will inherite from the Model class which defines a set
#- of properties and methods to handle the several datatypes.
#-
#- The code below will allow django to:
#-    * Create the database holding the app data.
#-    * Create the python handles to access that database.
#---------------------------------------------------------------
USERNAME_MAX_LENGTH = 10
PASSWORD_MIN_LENGTH = 7
PASSWORD_MAX_LENGTH = 20
EMAIL_MAX_LENGTH = 100

QUESTION_MAX_LENGTH = 200
CHOICE_MAX_LENGTH = 200
CHOICE_MIN_FIELDS = 2
CHOICE_MAX_FIELDS = 7

class Poll(models.Model):
	question = models.CharField(max_length=QUESTION_MAX_LENGTH)
	opened_by = models.ForeignKey(User)
	opened_on = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_on = models.DateTimeField(auto_now_add=False, auto_now=True)

	class Meta:
		permissions = (("vote", "Can vote on polls"),
		               ("view_results", "Can watch results"))

	def __unicode__(self):
		return force_unicode(self.question)
		
	def get_choices(self, for_form=False):
		if for_form:
			return [(c.pk, c.option) for c in self.choice_set.all()]
		else:
			return [c.option for c in self.choice_set.all()]

	def get_total_votes(self):
		return sum([choice.votes for choice in self.choice_set.all()])

	def get_voters(self):
		return [user.id for user in choice.voted_by.all() for choice in self.choice_set.all()]

	def get_voters_id(self):
		return [user.id for user in choice.voted_by.all() for choice in self.choice_set.all()]

class Choice(models.Model):
	option = models.CharField(max_length=CHOICE_MAX_LENGTH)
	for_poll = models.ForeignKey(Poll)
	votes = models.IntegerField(default=0)
	voted_by = models.ManyToManyField(User)

	def __unicode__(self):
		return force_unicode(self.option)

class UserChangeForm(forms.ModelForm):
	password = forms.CharField(max_length=PASSWORD_MAX_LENGTH, required=False, widget=forms.PasswordInput, help_text="Leave this field blank to keep the current password.")
	confirm_password = forms.CharField(max_length=PASSWORD_MAX_LENGTH, required=False, widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ("first_name", "last_name", "username", "email", "password", "confirm_password",)

	def clean(self):
		super(UserChangeForm, self).clean()
		data = self.cleaned_data.get("confirm_password")
		password = self.cleaned_data.get("password")
		if data and password and data != password:
				raise forms.ValidationError("Passwords do not match.")
		
	def save(self, commit=True):
		user = super(UserChangeForm, self).save(commit=False)
		password = self.cleaned_data.get("password")
		if password: user.set_password(password)
		if commit:
			user.save()
		return user

class PollForm(forms.ModelForm):

	class Meta:
		model = Poll
		fields = ("question",)

class ChoiceForm(forms.ModelForm):

	class Meta:
		model = Choice
		fields = ("option",)

ChoiceFormset = forms.formset_factory(ChoiceForm, extra=0, min_num=CHOICE_MIN_FIELDS, max_num=CHOICE_MAX_FIELDS, validate_min=True, validate_max=True)

class VoteForm(forms.Form):
	option_set = forms.ChoiceField(choices=[], widget=forms.RadioSelect)

polls/forms.py
from django import forms
from django.forms.utils import ErrorList
from django.contrib.auth.models import User

USERNAME_MAX_LENGTH = 10
EMAIL_MAX_LENGTH = 50
PASSWORD_MIN_LENGTH = 7

class SpanErrorList(ErrorList):

	def __unicode__(self):
		return self.as_span()
		
	def as_span(self):
		if not self: return ""
		return " ".join([e for e in self])

class SignUpForm(forms.Form):

	username = forms.CharField(max_length=USERNAME_MAX_LENGTH)
	email = forms.EmailField(max_length=EMAIL_MAX_LENGTH)
	password1 = forms.CharField(label='Password', min_length=PASSWORD_MIN_LENGTH, widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirm password', min_length=PASSWORD_MIN_LENGTH, widget=forms.PasswordInput)

	def clean_username(self):
		data = self.cleaned_data['username']
		try:
			user = User.objects.get(username=data)
			raise forms.ValidationError('This username is already taken.')
		except User.DoesNotExist:
			return data

	def clean_password2(self):
		try:
			data1 = self.cleaned_data['password1']
		except KeyError:
			raise forms.ValidationError('This field is required.')
		try:
			data2 = self.cleaned_data['password2']
		except KeyError:
			raise forms.ValidationError('This field is required.')

		if data1 and data2 and data1 != data2: raise forms.ValidationError('Passwords does not match.')
		return data2

	def clean_email(self):
		data = self.cleaned_data['email']
		try:
			user = User.objects.get(email=data)
			raise forms.ValidationError('This email is already in use.')
		except User.DoesNotExist:
			return data

class LogInForm(forms.Form):
	username = forms.CharField(max_length=USERNAME_MAX_LENGTH)
	password = forms.CharField(label='Password', widget=forms.PasswordInput)

class ChoiceForm(forms.Form):	
	choice_text = forms.ChoiceField(choices=[], widget=forms.RadioSelect)
	
	def set_question_text(self, question):
		self.question_text = question.question_text

	def set_question_pk(self, question):
		self.question_pk = question.pk

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.utils import timezone
from django.utils.decorators import method_decorator

from django.views.generic import RedirectView, ListView, DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import Permission
from django.contrib.auth.forms import UserCreationForm

from .models import CHOICE_MIN_FIELDS, CHOICE_MAX_FIELDS
from .models import User, Choice, Poll, UserChangeForm, PollForm, ChoiceFormset, VoteForm
from .auth import *

class SignupView(CreateView):
	template_name = "polls/signup.html"
	model = User
	form_class = UserCreationForm

	def form_valid(self, form):
		self.object = form.save()
		
		polls_permissions = Permission.objects.filter(content_type__app_label="polls")
		for polls_perm in polls_permissions: self.object.user_permissions.add(polls_perm)

		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password1")

		user = authenticate(username=username, password=password)
		if user != None:
			if user.is_active:
				login(self.request, user)
				messages.add_message(self.request, messages.SUCCESS, "Welcome aboard, %s!"%username)
			else:
				messages.add_message(self.request, messages.ERROR, "Oops, it appears that your account started disabled.")
		else:
			messages.add_message(self.request, messages.ERROR, "Oh no! Something went wrong. Contact your favorite developer to fix this.")
			return redirect("polls:signup", permanent=False)

		return redirect("polls:index", permanent=False)
		
class UserAccountView(UpdateView):
	template_name = "polls/user_account.html"
	model = User
	form_class = UserChangeForm

	@method_decorator(login_required(message="You need to be logged in before updating your account."))
	@method_decorator(user_account_ownership_required)
	def dispatch(self, request, *args, **kwargs):
		return super(UserAccountView, self).dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		self.object = form.save()

		messages.add_message(self.request, messages.SUCCESS, "Your account was updated.")
		return redirect("polls:index", permanent=False)

class CreatePollView(FormView):
	template_name = "polls/create_poll.html"

	@method_decorator(login_required(message="You need to be logged in before opening a new poll."))
	@method_decorator(permission_required(["polls.add_poll", "polls.add_choice"], raise_exception=True))
	def distpatch(self, request, *args, **kwargs):
		return super(CreatePollView, self).dispatch(request, *args, **kwargs)

	def get(self, request):
		return render(request, self.template_name, context={"question_form": PollForm(), "choice_forms": ChoiceFormset()})

	def post(self, request):
		question_form = PollForm(request.POST)
		choice_forms = ChoiceFormset(request.POST)

		if question_form.is_valid() and choice_forms.is_valid():
			return self.form_valid((question_form, choice_forms))
		else:
			return self.form_invalid((question_form, choice_forms))

	def form_invalid(self, forms):
		question_form, choice_forms = forms
		return render(self.request, self.template_name, context={"question_form": question_form, "choice_forms": choice_forms})

	def form_valid(self, forms):
		question_form, choice_forms = forms

		current_user = User.objects.get(id=self.request.user.id)
		question = Poll(question=question_form.cleaned_data["question"], opened_by=current_user)
		question.save()
		choices = []
		for choice_form in choice_forms:
			choice = Choice(for_poll_id=question.id, option=choice_form.cleaned_data["option"])
			choice.save()
			
		return redirect("polls:index", permanent=False)

class UpdatePollView(FormView):
	template_name = "polls/update_poll.html"

	@method_decorator(login_required(message="You need to be logged in before updating your polls."))
	@method_decorator(user_poll_ownership_required)
	@method_decorator(poll_no_votes_required)
	def dispatch(self, request, *args, **kwargs):
		self.question = Poll.objects.get(pk=kwargs.pop("pk"))
		
		self.initial_question = {"question": self.question.question}
		self.choices = self.question.choice_set.all()
		self.initial_choices_values = [c.option for c in self.choices]
		self.num_choices = self.choices.count()
		
		self.initial_formset = [{"form-TOTAL_FORMS": self.num_choices,
		                         "form-INITIAL_FORMS": self.num_choices,
		                         "form-MIN_NUM_FORMS": CHOICE_MIN_FIELDS,
		                         "form-MAX_NUM_FORMS": CHOICE_MAX_FIELDS}]

		self.initial_choices = []
		for i in xrange(self.num_choices):
			self.initial_choices.append(dict(option=self.choices[i].option))
			self.initial_formset.append({"form-"+str(i)+"-choice": self.choices[i].option})

		return super(UpdatePollView, self).dispatch(request, *args, **kwargs)

	def get(self, request):
		question_form = PollForm(initial=self.initial_question)
		choice_forms = ChoiceFormset(initial=self.initial_choices)
		
		return render(request, self.template_name, context={"question_form": question_form,
		                                                    "choice_forms": choice_forms,
		                                                    "poll": self.question})

	def post(self, request):
		question_form = PollForm(data=request.POST, initial=self.initial_question)
		choice_forms = ChoiceFormset(data=request.POST, initial=self.initial_formset)
		
		if question_form.is_valid() and choice_forms.is_valid():
			return self.form_valid((question_form, choice_forms))
		else:
			return self.form_invalid((question_form, choice_forms))

	def form_invalid(self, forms):
		question_form, choice_forms = forms
		return render(self.request, self.template_name, context={"question_form": question_form, "choice_forms": choice_forms})

	def form_valid(self, forms):
		question_form, choice_forms = forms

		if question_form.has_changed():
			self.question.question = question_form.cleaned_data["question"]
			self.question.save()

		current_choices = [d["option"] for d in choice_forms.cleaned_data]
		current_choices_num = choice_forms.total_form_count()

		if choice_forms.has_changed():
			if self.num_choices == current_choices_num:
				for i, choice_form in enumerate(choice_forms):
					if choice_form.has_changed():
						self.choices[i].option = choice_form.cleaned_data["option"]
						self.choices[i].save()
			else:
				diff_num = current_choices_num - self.num_choices
				
				if diff_num < 0:
					i = 0
					while diff_num < 0:
						del_choice = self.choices[i]
						if not del_choice.option in current_choices:
							del_choice.delete()
							diff_num += 1
						i += 1
					for i, choice_form in enumerate(choice_forms):
						if not choice_form.cleaned_data["option"] in self.initial_choices_values:
							self.choices[i].option = choice_form.cleaned_data["option"]
							self.choices[i].save()
				else:
					for i, choice_form in enumerate(choice_forms):
						if choice_form.has_changed():
							try:
								self.choices[i].option = choice_form.cleaned_data["option"]
								self.choices[i].save()
							except IndexError:
								new_choice = Choice(for_poll_id=self.question.id, option=choice_form.cleaned_data["option"])
								new_choice.save()
			
		return redirect("polls:index", permanent=False)

class DeletePollView(RedirectView):
	permanent = False
	pattern_name = "polls:index"

	@method_decorator(login_required(message="You need to be logged in before deleting any poll."))
	@method_decorator(user_poll_ownership_required)
	@method_decorator(poll_no_votes_required)
	def dispatch(self, request, *args, **kwargs):
		question = Poll.objects.get(pk=kwargs.pop("pk"))
		question.delete()
		return super(DeletePollView, self).dispatch(request, *args, **kwargs)

class IndexView(ListView):
	model = Poll
	template_name = "polls/index.html"
	context_object_name = "poll_list"
	
	def get_context_data(self, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)
		context.update(polluser=self.request.user)
		return context

class VotePollView(FormView):
	template_name = "polls/vote.html"
	form_class = VoteForm

	@method_decorator(login_required(message="You need to be logged in before voting in any poll."))
	@method_decorator(permission_required("polls.vote", raise_exception=True))
	@method_decorator(user_no_vote_required)
	def dispatch(self, request, *args, **kwargs):
		self.question = Poll.objects.get(pk=kwargs.pop("pk"))
		self.choices = self.question.get_choices(for_form=True)

		return super(VotePollView, self).dispatch(request, *args, **kwargs)

	def get_form(self):
		form = super(VotePollView, self).get_form()
		form.fields["option_set"].choices = self.choices
		return form

	def get_context_data(self, **kwargs):
		kwargs.update(poll=self.question)
		return super(VotePollView, self).get_context_data(**kwargs)

	def form_valid(self, form):
		selected_choice = self.question.choice_set.get(pk=form.cleaned_data.get("option_set"))
		selected_choice.voted_by.add(self.request.user)
		selected_choice.votes = selected_choice.voted_by.count()
		selected_choice.save()
		return redirect("polls:results", permanent=False, pk=self.question.pk)

class ResultsPollView(DetailView):
	template_name = "polls/results.html"
	model = Poll

	@method_decorator(login_required(message="You need to be logged in before you can view any results."))
	@method_decorator(permission_required("polls.view_results", raise_exception=True))
	@method_decorator(user_vote_required)
	def dispatch(self, request, *args, **kwargs):
		return super(ResultsPollView, self).dispatch(request, *args, **kwargs)

polls/templates/polls/create_poll.html
{% extends "base_template.html" %}
{% load staticfiles %}

{% block add_styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/form_style.css' %}">
{% endblock %}

{% block flash_messages_block %}
	{% with flash_messages=messages %}
		{% for message in flash_messages %}
			<div class="{{ message.tags }}">{{ message }}</div>
		{% endfor %}
	{% endwith %}
{% endblock %}

{% block page_title %}Create your poll{% endblock %}

{% block page_body %}
	{% with flash_messages=question_form.non_field_errors|add:choice_forms.non_form_errors %}
		{% for message in flash_messages %}
			<div class="error">{{ message }}</div>
		{% endfor %}
	{% endwith %}
	<form action="{% url 'polls:create-poll' %}" method="post">
		{% csrf_token %}
		<div class="field-wrapper">
			<label>{{ question_form.question.label }}:</label>
			{{ question_form.question }}
			<div class="error-field">
				{{ question_form.question.errors }}
			</div>
		</div>
		<div id="formset-placeholder">
			{{ choice_forms.management_form }}
			<div class="add-wrapper">
				<input type="button" class="button-sm add" value="add">
			</div>
			{% for choice_form in choice_forms.forms %}
				<div class="dynamic-wrapper">
						<label>{{ choice_form.option.label }} #{{ forloop.counter }}:</label>
						{{ choice_form.option }}
						<input type="button" class="button-sm del" value="delete">
					<div class="error-field">
						{{ choice_form.option.errors }}
					</div>
				</div>
			{% endfor %}
		</div>
		<input type="submit" value="Create"/>
		<a href="{% url 'polls:index' %}" class="button-md del">Cancel</a>
	</form>
{% endblock %}

{% block js %}
	<script src="{% static 'polls/js/formset_handler.js' %}"></script>
{% endblock %}

polls/templates/polls/index.html
{% extends "base_template.html" %}
{% load staticfiles %}

{% block add_styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/index_style.css' %}">
{% endblock %}

{% block flash_messages_block %}
	{% with flash_messages=messages %}
		{% for message in flash_messages %}
			<div class="{{ message.tags }}">{{ message }}</div>
		{% endfor %}
	{% endwith %}
{% endblock %}

{% block page_title %}Active Polls{% endblock %}

{% block page_body %}
	{% if object_list %}
		{% for poll in object_list %}
			<div class="poll-container">
				<div class="poll-item">
					<a href="{% url 'polls:vote' poll.pk %}" class="question">{{ poll.question }}</a>
				</div>
				<div class="poll-info">
					<p class="date">Opened on {{ poll.opened_on|date:"d M, Y" }} by {{ poll.opened_by }}</p>
					<a href="{% url 'polls:results' poll.pk %}" class="voted">{{ poll.get_total_votes }}<span>vote{{ poll.get_total_votes|pluralize }}</span></a>
				</div>
			</div>
			<div class="actions">
				{% if user.is_authenticated and poll.get_total_votes == 0 and poll.opened_by == user or user.is_superuser %}
					<a href="{% url 'polls:update-poll' poll.pk %}" class="button-sm add">Update</a>
					<a href="{% url 'polls:delete-poll' poll.pk %}" class="button-sm del">Delete</a>
				{% else %}
					<a href="{% url 'polls:update-poll' poll.pk %}" class="button-sm disabled">Update</a>
					<a href="{% url 'polls:delete-poll' poll.pk %}" class="button-sm disabled">Delete</a>
				{% endif %}
			</div>
		{% endfor %}
	{% else %}
		<div id="empty">No polls here... :(</div>
	{% endif %}
{% endblock %}

polls/templates/polls/login.html
{% extends "base_template.html" %}
{% load staticfiles %}

{% block add_styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/form_style.css' %}">
{% endblock %}

{% block flash_messages_block %}
	{% with flash_messages=messages %}
		{% for message in flash_messages %}
			<div class="{{ message.tags }}">{{ message }}</div>
		{% endfor %}
	{% endwith %}
{% endblock %}

{% block page_title %}Sign in to start your polling now!{% endblock %}

{% block page_body %}
	<div id="form-message-container">
		{% with flash_messages=form.non_field_errors %}
			{% for message in flash_messages %}
				<div class="error">{{ message }}</div>
			{% endfor %}
		{% endwith %}
	</div>
	<form action="{% url 'polls:login' %}" method="post">
		{% csrf_token %}
		<input type="hidden" name="next" value="{{ next }}">
		<div class="field-wrapper">
			<label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
			{{ form.username }}
			<div class="error-field">
				{{ form.username.errors }}
			</div>
		</div>
		<div class="field-wrapper">
			<label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
			{{ form.password }}
			<div class="error-field">
				{{ form.password.errors }}
			</div>
		</div>
		<input type="submit" value="Sign in"/>
	</form>
{% endblock %}

polls/templates/polls/update_poll.html
{% extends "base_template.html" %}
{% load staticfiles %}

{% block add_styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/form_style.css' %}">
{% endblock %}

{% block flash_messages_block %}
	{% with flash_messages=messages %}
		{% for message in flash_messages %}
			<div class="{{ message.tags }}">{{ message }}</div>
		{% endfor %}
	{% endwith %}
{% endblock %}

{% block page_title %}Update your poll{% endblock %}

{% block page_body %}
	{% with flash_messages=question_form.non_field_errors|add:choice_forms.non_form_errors %}
		{% for message in flash_messages %}
			<div class="error">{{ message }}</div>
		{% endfor %}
	{% endwith %}
	<form action="{% url 'polls:update-poll' poll.pk %}" method="post">
		{% csrf_token %}
		<div class="field-wrapper">
			<label>{{ question_form.question.label }}:</label>
			{{ question_form.question }}
			<div class="error-field">
				{{ question_form.question.errors }}
			</div>
		</div>
		<div id="formset-placeholder">
			{{ choice_forms.management_form }}
			<div class="add-wrapper">
				<input type="button" class="button-sm add" value="add">
			</div>
			{% for choice_form in choice_forms.forms %}
				<div class="dynamic-wrapper">
						<label>{{ choice_form.option.label }} #{{ forloop.counter }}:</label>
						{{ choice_form.option }}
						<input type="button" class="button-sm del" value="delete">
					<div class="error-field">
						{{ choice_form.option.errors }}
					</div>
				</div>
			{% endfor %}
		</div>
		<input type="submit" value="Update"/>
		<a href="{% url 'polls:index' %}" class="button-md del">Cancel</a>
	</form>
{% endblock %}

{% block js %}
	<script src="{% static 'polls/js/formset_handler.js' %}"></script>
{% endblock %}

polls/templates/polls/user_account.html
{% extends "base_template.html" %}
{% load staticfiles %}

{% block add_styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/form_style.css' %}">
{% endblock %}

{% block flash_messages_block %}
	{% with flash_messages=messages %}
		{% for message in flash_messages %}
			<div class="{{ message.tags }}">{{ message }}</div>
		{% endfor %}
	{% endwith %}
{% endblock %}

{% block page_title %}Update your account{% endblock %}

{% block page_body %}
	<div id="form-message-container">
		{% with flash_messages=form.non_field_errors %}
			{% for message in flash_messages %}
				<div class="error">{{ message }}</div>
			{% endfor %}
		{% endwith %}
	</div>
	<form action="{% url 'polls:accounts' user.pk %}" method="post">
		{% csrf_token %}
		<div class="field-wrapper">
			<label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
			{{ form.first_name }}
			<div class="error-field">
				{{ form.first_name.errors }}
			</div>
		</div>
		<div class="field-wrapper">
			<label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
			{{ form.last_name }}
			<div class="error-field">
				{{ form.last_name.errors }}
			</div>
		</div>
		<div class="field-wrapper">
			<label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
			{{ form.username }}
			<div class="error-field">
				{{ form.username.errors }}
			</div>
		</div>
		<div class="field-wrapper">
			<label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
			{{ form.email }}
			<div class="error-field">
				{{ form.email.errors }}
			</div>
		</div>
		<div class="field-wrapper">
			<label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
			{{ form.password }}
			<div class="error-field">
				{{ form.password.errors }}
			</div>
		</div>
		<div class="field-wrapper">
			<label for="{{ form.confirm_password.id_for_label }}">{{ form.confirm_password.label }}</label>
			{{ form.confirm_password }}
			<div class="error-field">
				{{ form.confirm_password.errors }}
			</div>
		</div>
		<input type="submit" value="Update"/>
		<a href="{% url 'polls:index' %}" class="button-md del">Cancel</a>
	</form>
{% endblock %}

polls/templates/polls/vote.html
{% extends "base_template.html" %}
{% load staticfiles %}

{% block add_styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/form_style.css' %}">
{% endblock %}

{% block flash_messages_block %}
	{% with flash_messages=messages %}
		{% for message in flash_messages %}
			<div class="{{ message.tags }}">{{ message }}</div>
		{% endfor %}
	{% endwith %}
{% endblock %}

{% block page_title %}{{ poll.question }}{% endblock %}

{% block page_body %}
	<div id="form-message-container">
		{% with flash_messages=form.non_field_errors %}
			{% for message in flash_messages %}
				<div class="error">{{ message }}</div>
			{% endfor %}
		{% endwith %}
	</div>
	<form action="{% url 'polls:vote' poll.pk %}" method="post">
		{% csrf_token %}
		<div class="field-wrapper">
			{{ form.option_set }}
			<div class="error-field">
				{{ form.option_set.errors }}
			</div>
		</div>
		<input type="submit" value="Vote"/>
		<a href="{% url 'polls:index' %}" class="button-md del">Cancel</a>
	</form>
{% endblock %}