polls/urls.py
#---------------------------------------------------------------
#- In this file I will define the url patterns of my polls app.
#---------------------------------------------------------------
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
               url(r"^$", views.IndexView.as_view(), name="index"),
               url(r"^signup$", views.SignupView.as_view(), name="signup"),
               url(r"^login$", login, kwargs={"template_name": "polls/login.html"}, name="login"),
               url(r"^accounts/(?P<pk>[0-9]+)$", views.UserAccountView.as_view(), name="accounts"),
               url(r"^logout$", logout, kwargs={"next_page": "polls:index"}, name="logout"),
               url(r"^create$", views.CreatePollView.as_view(), name="create-poll"),
               url(r"^update/(?P<pk>[0-9]+)$", views.UpdatePollView.as_view(), name="update-poll"),
               url(r"^delete/(?P<pk>[0-9]+)$", views.DeletePollView.as_view(), name="delete-poll"),
               url(r"^vote/(?P<pk>[0-9]+)$", views.VotePollView.as_view(), name="vote"),
               url(r"^results/(?P<pk>[0-9]+)$", views.ResultsPollView.as_view(), name="results"),
              ]

pollsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

# Examples:
# url(r'^$', 'pollsite.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),
#-----------------------------------------------------------
#- the url function takes te following arguments:
#-    * regex: regular expression to map againts defined
#-             urls.
#-    * view: the to which will be called upon the match.
#-    + kwargs: arguments passed to the target view.
#-    + name: name usde to reference across templates.
#-----------------------------------------------------------

urlpatterns = [
    url(r'^', include('polls.urls', namespace='polls')),               #- The ^ patterns are handled by polls.urls.
                                                                       #- The namespace is used to differenciate between
                                                                       #- views with the same name but different app.
    url(r'^admin/', include(admin.site.urls)),
]

templates/base_template.html
<!DOCTYPE HTML>
<html lang="eng">
  <head>
    {% load staticfiles %}
    <title>Polls Site</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/normalize.css' %}">
    <link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Lato:300,400,700'>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/base_style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    {% block add_styles %}
    {% endblock %}
  </head>
  <body>
		<header id="navigation">
				<a href="{% url 'polls:index' %}" id="logo">polls</a>
				<nav>
					{% if user.is_authenticated %}
						<a href="{% url 'polls:accounts' user.pk %}" id="username">{{ user.first_name|default:user.username }}</a>
						<a href="{% url 'polls:create-poll' %}">Create</a>
						<a href="{% url 'polls:logout' %}">Sign out</a>
					{% else %}
						<a href="{% url 'polls:signup' %}">Sign up</a>
						<a href="{% url 'polls:login' %}">Sign in</a>
					{% endif %}
				</nav>
		</header>
		<div id="flash-message-container">
			{% block flash_messages_block %}
			{% endblock %}
		</div>
			<div id="page-body">
				<h1 id="page-title">{% block page_title %}{% endblock %}</h1>
				{% block page_body %}
				{% endblock %}
			</div>
		
		<script>
			$(function() {
				var $DOM = $(document);
				var $message = $DOM.find(".error,.warning,.success");
				
				if($message)
					//$message.one("click", hideNow);
					$DOM.one("mousemove", hideWithDelay);

				//function hideNow(event) {
					//$message.fadeOut(500);
				//};
				function hideWithDelay() {
					$message.delay(4000).fadeOut("slow");
				};
			});
		</script>
		{% block js %}
		{% endblock %}
	</body>
</html>